### ISSUE TITLE
cart-popup.component.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [Zenon8/shop#2]
ngOnDestroy(): void {
    if (this.addSubscription) {
      this.addSubscription.unsubscribe();
    }
    if (this.visibilitySubscription) {
      this.visibilitySubscription.unsubscribe();
    }
  }
Зачем тут if? Подписка происходит в ngOnInit. Разве может быть такое, что подписка не будет создана?
Можно использовать this.addSubscription.add(anotherSub)
и this.addSubscription.unsubscribe() сразу отпишеться от основной подписки и от дочерних.

Аналогично тут cart.component.ts

**Comment by Zenon8** [comment]
Fixed.
