### ISSUE TITLE
Структура проекта

### ISSUE THREAD

**Issue by VZhyrytskiy** [Zenon8/shop#4]
У вас сейчас структура проекта разбита по типам сущностей. Для маленьких проектов - это ок, но для больших лучш разбивать по функционалу, а внутри уже по типам. 
Например
Товары
  Модели
  Компоненты
  Сервисы
Корзина
 Аналогично

**Comment by Zenon8** [comment]
Сделаю рефакторинг структуры проекта в таск2.
